name: Update README
on:
  schedule:
    - cron: '0 16 * * *' # S'exécute tous les jours à 16h00 (heure UTC)
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "feat: activity update cron"
          MAX_LINES: 10
          COMMIT_NAME: GitHub Activity Readme